my_dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: CGVHPFH-BGC40199
      user: GRAVIALEX
      password: Asdfrewq12345!
      role: ACCOUNTADMIN
      database: DBT_PROJECT
      warehouse: COMPUTE_WH
      schema: PUBLIC
      threads: 4
      client_session_keep_alive: false
