my_dbt_project:
  outputs:
    dev:
      account: CGVHPFH-BGC40199
      database: DBT_PROJECT
      password: Asdfrewq12345!
      role: ACCOUNTADMIN
      schema: ' PUBLIC'
      threads: 1
      type: snowflake
      user: GRAVIALEX
      warehouse: COMPUTE_WH
  target: dev
